### ISSUE TITLE
Fixed and Moveable elements are layered

### ISSUE THREAD

**Issue by cphilippsen** [corysimmons/slipScroll.js#1]
Hi, I've run into an issue where I have the fixed elements below the absolute elements. I have three elements(logo, nav and footer). Should every element have a unique class? Like fixed, fixed2, fixed3, moveable, moveable2, moveable3 in the same container or can I have the same class for every fixed and moveable element? All elements are position fixed in CSS too.

**Comment by corysimmons** [comment]
I believe the first element is the only one that needs to be fixed, the rest can have the same class: http://codepen.io/corysimmons/pen/lBKmG
